### ISSUE TITLE
Validacion Tpl con Jquery Validation

### ISSUE THREAD

**Issue by brianducca** [lkdml/UTN_PPS_2016#1]
Agregar todas las validaciones a las tpl

**Comment by LucasDaniel77** [comment]
El fin de semana me pongo con esto.

**Comment by LucasDaniel77** [comment]
Todas las validaciones terminadas. Dejo abierto por la modificación en campos custom, que no esta correctamente referenciada y falta validar.

**Comment by brianducca** [comment]
Revisar nuevamente validaciones de categoría anuncios, anuncios , SLA(en este necesita como obligatorio poner un tipo de ticket) y empresa

**Comment by LucasDaniel77** [comment]
Cuando este finalizada 100% la tpl completo las validaciones.
