### ISSUE TITLE
Grilla de tickets

### ISSUE THREAD

**Issue by brianducca** [lkdml/UTN_PPS_2016#11]
Podes acceder a ver los tickets, aunque no tengas vista sobre ese departamentos.
A su vez, revisar los links desde el dashboard , que redirigen a esa vista de la grilla.
También hacer que cuando te redirige del dashboard, en los links de los estados del ticket(cuadraditos), agregar un filtro mas al get, que sean los tickets del operador logeado.

**Comment by lkdml** [comment]
Ya está solucionado el bug, pero no estoy de acuerdo con que redirija a los ticket del operador. 
Ya que puede que el ticket recien generado no esté asignado al operador.
Probar si esta ok.

**Comment by brianducca** [comment]
si no esta asignado, entonces no forma parte del trabajo pendiente del operador, que es el motivo por el cual ese link esta en el dashboard. si coincidis, lo cerramos

**Comment by lkdml** [comment]
ahora si... ya está resuelto .. Teniendo un parametro por get que sea "Asignado", no importa el valor.. va a sumarle al criterio de la vista..
