### ISSUE TITLE
Utilización de la firma de Operador

### ISSUE THREAD

**Issue by lkdml** [lkdml/UTN_PPS_2016#15]
En ningun momento cuando creamos o respondemos un ticket, damos la posibilidad de que en el cuadro de texto se sume la firma del operador (si es que tenemos texto de respuesta).
- TPL:
Habria que agregar algun tipo de opcion que permita agregar la firma del operador.

- (opcion1) hacer un JS, que al utilizar la opcion del TPL, añada al textarea la firma del operador.

- (opcion2)ControladorAction:
Habría que armar una logica que permita identificar si hay texto en el cuerpo del mensaje, y añadirle la firma del operador si tiene flag activo.

**Comment by brianducca** [comment]
@lkdml @mlopezsenes  revisar si era lo pedido

**Comment by lkdml** [comment]
muy bueno.!
