### ISSUE TITLE
No funciona el boton de cerrar ticket en en ningun modo (operador/usuario)

### ISSUE THREAD

**Issue by lkdml** [lkdml/UTN_PPS_2016#17]
Hay que resolver esta problematica en usuarios y operadores.

**Comment by lkdml** [comment]
El funcionamietno deberia ser que al cerrar el ticket, se verifique si hay un mensaje, y si lo hay, deberia guardar el mensaje y cerrar el ticket.

La problematica que tenemos aca, es que si existe mas de un estado de cierre, habría que especificar de alguna forma cual es el estado por defecto que se debe tomas. pero creo que eso dará a pensar un poco mas el funcionamiento.

**Comment by brianducca** [comment]
Por lo que estoy viendo, ahora el usuario no puede ni cerrar ni cambiar de estado el ticket, como resolveríamos eso?

**Comment by brianducca** [comment]
resuelto frontend!

**Comment by lkdml** [comment]
y en el back no hace falta.. asi que cierro el issue
