### ISSUE TITLE
Crear una linea de tiempo en vista-ticket

### ISSUE THREAD

**Issue by lkdml** [lkdml/UTN_PPS_2016#23]
en ambos accesos al ver el ticket seria bueno poder contar con una linea de tiempo que permita ver graficamente los momentos del ticket.

esto debe reflejar los siguientes datos:
- fecha y hora de:
- Accion (estados, prioridades departamentos, asignaciones, sla)
- responsable.

**Comment by brianducca** [comment]
Terminado con commit [https://github.com/lkdml/UTN_PPS_2016/commit/60ac407bf9f992d80bf8acd9cf1ad1869c4c9541](url)

**Comment by brianducca** [comment]
Cerrado commit : 60ac407bf9f992d80bf8acd9cf1ad1869c4c9541
