### ISSUE TITLE
Re-hacer tpl de departamento

### ISSUE THREAD

**Issue by lkdml** [lkdml/UTN_PPS_2016#3]
El departemento.tpl solo muestra nombre y descripcion, cuando en realidad debe mostrar los datos que se guardan en la BD.

Como ya está hecho el action, deberiamos realizar las modificaciones manteniento los nombres de los input que debe recibir el action.

$_POST["nombre"]
$_POST["descripcion"]
$_POST["idDeptoPadre"]
$_POST["visibilidadUsuario"]
$_POST["orden"]
$_POST['operadorDefault']

Y revisar la entidad correspondiente, por si faltó algo.

**Comment by brianducca** [comment]
Listo la Lógica, falta corregir entidad y hacer el rediseño

**Comment by lkdml** [comment]
Ya está funcionando
