### ISSUE TITLE
Ticket Estado 

### ISSUE THREAD

**Issue by brianducca** [lkdml/UTN_PPS_2016#4]
Revisar entidad ,falta atributo ,getter y setter de "Nombre".También cuando resuelvas lo del orden de las prioridades del ticket, aplicarlo para estados!.
Luego de finalizado, reasignamelo asi termino las pruebas del ABM!.

**Comment by lkdml** [comment]
Lo que hice en prioridades fue por el momento desactivar el orden, hasta bien volver a analizar su utilización. Por lo que sugiero hacer los mismo en estados.
Ambas entidades ya permiten que se guarden sus valores como null.
En cuanto a la entidad TicketEstado ya tiene su atributo nombre.

**Comment by brianducca** [comment]
Terminado el abm, falta corregir de la tpl , acomodar la vista y el padding creo del checkbox, se lo paso a lucas
