### ISSUE TITLE
Categoria Anuncios y Anuncio

### ISSUE THREAD

**Issue by brianducca** [lkdml/UTN_PPS_2016#5]
Terminar la lógica de categoria anuncios y anuncios para que funcione el ABM, estaba buscando y categoria tiene un campo de icono. Estuve investigando y me tope con esto
http://victor-valencia.github.io/bootstrap-iconpicker/

Voy a ver de implementarlo que nos vendria bien.

**Comment by brianducca** [comment]
Terminado ABM Categoria anuncios, funcionando con el icon-picker, agregado también en la grilla.
Marian, necesito que modifiques la entidad de categorias anuncios porque en la BD acepta varchar(15) y algunos iconos ocupan mas de 15, y no se guarda bien, por ende no muestra nada, por favor cambiamelo a varchar(50) el tipo de la columna icono y cuando terminas reasignamelo asi termino con anuncio

**Comment by brianducca** [comment]
Actualizadas las entidades de CategoriaAnuncio y Anuncio, omití esto

**Comment by brianducca** [comment]
Finalizado, queda ver la funcion para los datetime

**Comment by lkdml** [comment]
Ya estan funcionando los datetimes
