### ISSUE TITLE
ABM SLA

### ISSUE THREAD

**Issue by brianducca** [lkdml/UTN_PPS_2016#7]
Deje funcionando el alta correctamente. Si podes revisa la modificación dado que no trae las hrs y pincha mas abajo en el template .En la baja lo maneje como baja lógica pero no estaría funcionando.

**Comment by brianducca** [comment]
ABM SLA funcionando, revisar el javascript que cuando tocas en borrar, sin necesidad de decir "si estoy seguro"/ "no sacame de aca" ya lo borra automaticamente(baja lógica). Por ahora deje esto: cuando editas un sla, si estaba de baja lógica, lo vuelve a poner activo.
Ver ahora el tema del checkbox de la grilla de sla y decidir que hacer con los que estan eliminados (si puede editarlos o directamente no mostrarlos en la grilla)

**Comment by LucasDaniel77** [comment]
@lkdml , sumé un Duration Picker limitado a tres días, parece estar funcionando. Hay que revisar si sirve.

**Comment by brianducca** [comment]
@LucasDaniel77  mejor sacalo y dejalo como estaba dado que siempre van a ser horas. Una vez hecho, cerra el issue

**Comment by LucasDaniel77** [comment]
Ya lo eliminé y valido que se ingrese un int de 1 a 72.
