### ISSUE TITLE
CheckBox de Grillas, botón Borrar

### ISSUE THREAD

**Issue by brianducca** [lkdml/UTN_PPS_2016#8]
No importa que grilla sea, cuando tocas click en borrar, ya ejecuta el action de borrar, sin importar que opción pongas en el modal. En las grillas de usuario y sla pasa, calculo que debe ser en todas

**Comment by LucasDaniel77** [comment]
Yo lo arreglo, es el name y value que están definidos en el boton Borrar de la grilla y no en el Modal.

**Comment by LucasDaniel77** [comment]
Implementé un js en todas las tpl (borradoModal.js) y cambié los parametros sobre el boton confirmarBorrado.
