### ISSUE TITLE
Caracteres especiales

### ISSUE THREAD

**Issue by brianducca** [lkdml/UTN_PPS_2016#9]
Corregir el guardado y la muestra de caracteres especiales como acentos o la ñ que se esta mostrando de forma incorrecta

**Comment by LucasDaniel77** [comment]
Volví el caracterset para atrás porque el otro rompe más de lo que soluciona. Estoy investigando porque utf-8 no lee los tildes (debería, creo que el problema es php)

**Comment by lkdml** [comment]
creo que ahora si, el tema está resuelto... agregúe el encoding a doctrine, para que sea uniforme en todo el sitio. el encoding que quedo es utf-8
